"""
Export utilities for the RAG Document Q&A Chatbot.
Supports exporting chat history as PDF or JSON.
"""

import json
from datetime import datetime
from typing import List
from fpdf import FPDF


def export_chat_to_json(messages: List[dict]) -> str:
    """Convert chat history to a formatted JSON string.

    Args:
        messages: List of message dicts with 'role' and 'content' keys.

    Returns:
        Pretty-printed JSON string.
    """
    export_data = {
        "exported_at": datetime.now().isoformat(),
        "total_messages": len(messages),
        "conversation": [
            {"role": msg["role"], "content": msg["content"]}
            for msg in messages
        ],
    }
    return json.dumps(export_data, indent=2, ensure_ascii=False)


def export_chat_to_pdf(messages: List[dict]) -> bytes:
    """Generate a PDF from chat history.

    Each Q&A pair is rendered with a bold question header and plain answer body.

    Args:
        messages: List of message dicts with 'role' and 'content' keys.

    Returns:
        Raw PDF bytes ready for download.
    """
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # ── Title ──
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 12, "RAG Document Q&A - Chat Export", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 6, f"Exported on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(8)

    # ── Divider ──
    pdf.set_draw_color(102, 126, 234)
    pdf.set_line_width(0.5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(8)

    # ── Messages ──
    pair_number = 0
    for msg in messages:
        role = msg["role"]
        # Sanitise content: replace characters the built-in font can't render
        content = msg["content"].encode("latin-1", "replace").decode("latin-1")

        if role == "user":
            pair_number += 1
            # Question header
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(102, 126, 234)
            pdf.cell(0, 8, f"Q{pair_number}:", new_x="LMARGIN", new_y="NEXT")
            # Question body
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(30, 30, 30)
            pdf.multi_cell(0, 6, content)
            pdf.ln(3)

        elif role == "assistant":
            # Answer header
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(118, 75, 162)
            pdf.cell(0, 8, f"A{pair_number}:", new_x="LMARGIN", new_y="NEXT")
            # Answer body
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(50, 50, 50)
            pdf.multi_cell(0, 6, content)
            pdf.ln(5)

            # Light separator between Q&A pairs
            pdf.set_draw_color(200, 200, 220)
            pdf.set_line_width(0.2)
            pdf.line(15, pdf.get_y(), 195, pdf.get_y())
            pdf.ln(5)

    # ── Footer note ──
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 6, "Generated by RAG Document Q&A Chatbot | Developed by Yaseen Mahek", align="C")

    return bytes(pdf.output())
